name: Test

on:
  push:
    branches: [ main, feature/*, fix/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
#        copy C:\\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\osgeo\gdalplugins\disabled\ogr_FileGDB.dll C:\\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\osgeo\gdalplugins\ogr_FileGDB.dll
        curl https://raw.githubusercontent.com/Esri/file-geodatabase-api/master/FileGDB_API_1.5.1/FileGDB_API_1_5_1-VS2017.zip -o FileGDB_API.zip
        mkdir filegdb_api
        tar.exe -xf FileGDB_API.zip -C filegdb_api
        copy .\filegdb_api\bin64\FileGDBAPI.dll C:\\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\osgeo\FileGDBAPI.dll
    - name: Run Tests
      run: |
        python -m pytest